In [9]:
#Exercici 1

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("wineData.txt", header=None)

# Assignem les columnes a la data
col_names = ["Class", "Alcohol", "Malic acid", "Ash", "Alcalinity of ash", 
             "Magnesium", "Total phenols", "Flavanoids", "Nonflavanoid phenols",
             "Proanthocyanins", "Color intensity", "Hue", "OD280/OD315 of diluted wines",
             "Proline"]
df.columns = col_names


X = df.drop("Class", axis=1)
y = df["Class"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Entrenem models de classificació diferents
model1 = KNeighborsClassifier(n_neighbors=5)
model1.fit(X_train, y_train)

model2 = RandomForestClassifier(n_estimators=100)
model2.fit(X_train, y_train)


RandomForestClassifier()

In [11]:
#Exercici 2

# Prediccions
y_pred1 = model1.predict(X_test)
y_pred2 = model2.predict(X_test)

# Evaluar la precisió dels models
acc1 = accuracy_score(y_test, y_pred1)
acc2 = accuracy_score(y_test, y_pred2)

# Comparar la precisió dels models
print("Precisió de KNeighborsClassifier:", acc1)
print("Precisió de RandomForestClassifier:", acc2)

# Escollim el model amb la precisió més alta
if acc1 > acc2:
    print('El model KNN és millor.')
else:
    print('El model Random Forest és millor.')

# Calculem la matriu de confusió dels models
conf_matrix1 = confusion_matrix(y_test, y_pred1)
conf_matrix2 = confusion_matrix(y_test, y_pred2)

# Printejar la matriu de confusió
print("\nConfusion matrix of KNeighborsClassifier:")
print(conf_matrix1)

print("\nConfusion matrix of RandomForestClassifier:")
print(conf_matrix2)


Precisió de KNeighborsClassifier: 0.7222222222222222
Precisió de RandomForestClassifier: 1.0
El model Random Forest és millor.

Confusion matrix of KNeighborsClassifier:
[[12  0  2]
 [ 0 11  3]
 [ 2  3  3]]

Confusion matrix of RandomForestClassifier:
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]


In [16]:
#Exercici 3

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000], 'penalty': ['l1', 'l2']}
logreg = LogisticRegression(solver='saga', max_iter=10000)
logreg_cv = GridSearchCV(logreg, param_grid, cv=5)
logreg_cv.fit(X_train, y_train)

print("Millors paràmetres:", logreg_cv.best_params_)
print("Precisió de validació:", logreg_cv.best_score_)



Millors paràmetres: {'C': 0.1, 'penalty': 'l2'}
Precisió de validació: 0.9012315270935961


In [18]:
#Exercici 4

import numpy as np
from sklearn.model_selection import cross_val_score

scores = cross_val_score(logreg_cv, X_train, y_train, cv=5)
print("Precisió mitjana:", np.mean(scores))
print("Desviació estàndard de la precisió:", np.std(scores))


Precisió mitjana: 0.8805418719211824
Desviació estàndard de la precisió: 0.06458182562624086


In [26]:
#Exercici 5

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

logreg_scaled = LogisticRegression()
logreg_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = logreg_scaled.predict(X_test_scaled)
accuracy_scaled = accuracy_score(y_test, y_pred_scaled)

print("Precisió (després de l'estandardització):", accuracy_scaled, "\n\nAixò significa que el model té una precisió del 100% després de l'estandardització de les dades. Això és un resultat excel·lent i probablement indica que el model està sobreajustat. Pot ser útil avaluar el model en dades de prova per assegurar-se que la seva capacitat de generalització és bona.")

Precisió (després de l'estandardització): 1.0 

Això significa que el model té una precisió del 100% després de l'estandardització de les dades. Això és un resultat excel·lent i probablement indica que el model està sobreajustat. Pot ser útil avaluar el model en dades de prova per assegurar-se que la seva capacitat de generalització és bona.


In [22]:
from sklearn.metrics import accuracy_score

# entrenem el model en les dades d'entrenament normalitzades
logreg_cv.fit(X_train_scaled, y_train)

# Prediccions en les dades de prova
y_pred = logreg_cv.predict(X_test_scaled)

# Avaluem la precisió del model en les dades de prova
test_accuracy = accuracy_score(y_test, y_pred)
print("Precisió en les dades de prova:", test_accuracy)


Precisió en les dades de prova: 1.0
