In [4]:
#Exercici 1

import numpy as np

def Exercici1():
    a =  np.array([[1,1,1],[2,2,2],[3,3,3]])
    if len(a.shape)>1:
        print("Error: the array has more than 1 dimension")
Exercici1()

Error: the array has more than 1 dimension


In [9]:
#Exercici 2

def Exercici2():
    matrix = np.random.randint(0,100,size=(4,4))
    print(matrix)
Exercici2()

[[70 54 62 76]
 [51 28 92 31]
 [53 38  1 73]
 [66 59 42 12]]


In [19]:
#Exercici 3

matrix = np.random.randint(0,10,size=(3,4))
def Exercici3(matrix):
    print(matrix)
    print("SUM Fila:",np.sum(matrix, axis=1))
    print("SUM Columna:",np.sum(matrix, axis=0))
Exercici3(matrix)

[[1 7 9 0]
 [5 4 1 4]
 [4 1 4 9]]
SUM Fila: [17 14 18]
SUM Columna: [10 12 14 13]


In [22]:
#Exercici 4

import pandas as pd

def Exercici4():
    data = {'A': [12,8,67,16,2],
            'B': [19,47,36,13,22],
            'C': [5,12,76,56,27]
            }
    df = pd.DataFrame(data,columns=['A','B','C'])
    correlacio = df.corr()
    print (correlacio)
  
Exercici4()

          A         B         C
A  1.000000  0.269442  0.793270
B  0.269442  1.000000 -0.063374
C  0.793270 -0.063374  1.000000
